### ISSUE TITLE
Keycloak UI Figma Prototype

### ISSUE THREAD

**Issue by RudhraBharathy** [ShadowHokageForge/event-management-system#8]
Each task specifies each page
- [x] Sign up
- [x] Sign In
- [x] Forget Password
- [x] Update Password
- [x] Email Verification
- [x] 2FA

**Comment by RudhraBharathy** [comment]
@SixPathsSage review the UI Design [Figma UI Design Link](https://www.figma.com/design/s2UbkzEpJyFh0xmsMhTgPZ/EMS---UI-Designs?node-id=0-1&t=6scbXTpkDjGxIQoE-1)

**Comment by SixPathsSage** [comment]
The design looks good
